from PyQt5 import uic
from PyQt5.QtWidgets import QMainWindow, QFileDialog
from PyQt5 import QtWidgets, QtGui, QtCore
from mrfix1033.melodybells.MelodyBells import MelodyBells


class MainWindow(QMainWindow):
    def __init__(self, melody_bells):
        super().__init__()
        self.melody_bells: MelodyBells = melody_bells
        self._init()

    def _init(self):
        self._init_ui()
        self._init_logic()

    def _init_ui(self):
        uic.loadUi("UI/main_window.ui", self)

    def _init_logic(self):
        self._connect()

    def _connect(self):
        self.pushButtonAddMelody.clicked.connect(self._add_melody)

    def _add_melody(self):
        files = QFileDialog.getOpenFileNames(self, self.melody_bells.localization.select_audio)
        if not files:
            return
        print(files)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.labelNearestBell = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelNearestBell.setFont(font)
        self.labelNearestBell.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelNearestBell.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNearestBell.setWordWrap(False)
        self.labelNearestBell.setObjectName("labelNearestBell")
        self.verticalLayoutMain.addWidget(self.labelNearestBell)
        self.tabsWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabsWidget.setObjectName("tabsWidget")
        self.tabMelodies = QtWidgets.QWidget()
        self.tabMelodies.setObjectName("tabMelodies")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabMelodies)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutMelodies = QtWidgets.QVBoxLayout()
        self.verticalLayoutMelodies.setSpacing(0)
        self.verticalLayoutMelodies.setObjectName("verticalLayoutMelodies")
        self.scrollAreaMelodies = QtWidgets.QScrollArea(self.tabMelodies)
        self.scrollAreaMelodies.setAcceptDrops(False)
        self.scrollAreaMelodies.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaMelodies.setAutoFillBackground(False)
        self.scrollAreaMelodies.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollAreaMelodies.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollAreaMelodies.setLineWidth(1)
        self.scrollAreaMelodies.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaMelodies.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollAreaMelodies.setWidgetResizable(True)
        self.scrollAreaMelodies.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollAreaMelodies.setObjectName("scrollAreaMelodies")
        self.scrollAreaWidgetContentsMelodies = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsMelodies.setGeometry(QtCore.QRect(0, 0, 977, 58))
        self.scrollAreaWidgetContentsMelodies.setMaximumSize(QtCore.QSize(16777215, 58))
        self.scrollAreaWidgetContentsMelodies.setObjectName("scrollAreaWidgetContentsMelodies")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContentsMelodies)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetMelodyElement = QtWidgets.QWidget(self.scrollAreaWidgetContentsMelodies)
        self.widgetMelodyElement.setEnabled(True)
        self.widgetMelodyElement.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widgetMelodyElement.setObjectName("widgetMelodyElement")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetMelodyElement)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutMelodyElement = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMelodyElement.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutMelodyElement.setObjectName("horizontalLayoutMelodyElement")
        self.labelMelodyElementNumber = QtWidgets.QLabel(self.widgetMelodyElement)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.labelMelodyElementNumber.setFont(font)
        self.labelMelodyElementNumber.setObjectName("labelMelodyElementNumber")
        self.horizontalLayoutMelodyElement.addWidget(self.labelMelodyElementNumber)
        self.lineEditMelodyElementName = QtWidgets.QLineEdit(self.widgetMelodyElement)
        self.lineEditMelodyElementName.setObjectName("lineEditMelodyElementName")
        self.horizontalLayoutMelodyElement.addWidget(self.lineEditMelodyElementName)
        self.labelMelodyElementDuration = QtWidgets.QLabel(self.widgetMelodyElement)
        self.labelMelodyElementDuration.setObjectName("labelMelodyElementDuration")
        self.horizontalLayoutMelodyElement.addWidget(self.labelMelodyElementDuration)
        self.pushButtonMelodyElementPlay = QtWidgets.QPushButton(self.widgetMelodyElement)
        self.pushButtonMelodyElementPlay.setObjectName("pushButtonMelodyElementPlay")
        self.horizontalLayoutMelodyElement.addWidget(self.pushButtonMelodyElementPlay)
        self.pushButtonMelodyElementSelect = QtWidgets.QPushButton(self.widgetMelodyElement)
        self.pushButtonMelodyElementSelect.setObjectName("pushButtonMelodyElementSelect")
        self.horizontalLayoutMelodyElement.addWidget(self.pushButtonMelodyElementSelect)
        self.pushButtonMelodyElementDelete = QtWidgets.QPushButton(self.widgetMelodyElement)
        self.pushButtonMelodyElementDelete.setObjectName("pushButtonMelodyElementDelete")
        self.horizontalLayoutMelodyElement.addWidget(self.pushButtonMelodyElementDelete)
        self.horizontalLayout_2.addLayout(self.horizontalLayoutMelodyElement)
        self.verticalLayout.addWidget(self.widgetMelodyElement)
        self.scrollAreaMelodies.setWidget(self.scrollAreaWidgetContentsMelodies)
        self.verticalLayoutMelodies.addWidget(self.scrollAreaMelodies)
        self.verticalLayout_3.addLayout(self.verticalLayoutMelodies)
        self.pushButtonAddMelody = QtWidgets.QPushButton(self.tabMelodies)
        self.pushButtonAddMelody.setObjectName("pushButtonAddMelody")
        self.verticalLayout_3.addWidget(self.pushButtonAddMelody)
        self.tabsWidget.addTab(self.tabMelodies, "")
        self.tabScheduler = QtWidgets.QWidget()
        self.tabScheduler.setObjectName("tabScheduler")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabScheduler)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayoutSchedulerTab = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSchedulerTab.setObjectName("horizontalLayoutSchedulerTab")
        self.groupBoxNewBell = QtWidgets.QGroupBox(self.tabScheduler)
        self.groupBoxNewBell.setObjectName("groupBoxNewBell")
        self.gridLayoutNewBell = QtWidgets.QGridLayout(self.groupBoxNewBell)
        self.gridLayoutNewBell.setObjectName("gridLayoutNewBell")
        self.horizontalLayoutNewBellDays = QtWidgets.QHBoxLayout()
        self.horizontalLayoutNewBellDays.setObjectName("horizontalLayoutNewBellDays")
        self.checkBoxNewBellDay1 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay1.setText("")
        self.checkBoxNewBellDay1.setObjectName("checkBoxNewBellDay1")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay1)
        self.checkBoxNewBellDay2 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay2.setText("")
        self.checkBoxNewBellDay2.setObjectName("checkBoxNewBellDay2")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay2)
        self.checkBoxNewBellDay3 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay3.setText("")
        self.checkBoxNewBellDay3.setObjectName("checkBoxNewBellDay3")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay3)
        self.checkBoxNewBellDay4 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay4.setText("")
        self.checkBoxNewBellDay4.setObjectName("checkBoxNewBellDay4")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay4)
        self.checkBoxNewBellDay5 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay5.setText("")
        self.checkBoxNewBellDay5.setObjectName("checkBoxNewBellDay5")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay5)
        self.checkBoxNewBellDay6 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay6.setText("")
        self.checkBoxNewBellDay6.setObjectName("checkBoxNewBellDay6")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay6)
        self.checkBoxNewBellDay7 = QtWidgets.QCheckBox(self.groupBoxNewBell)
        self.checkBoxNewBellDay7.setText("")
        self.checkBoxNewBellDay7.setObjectName("checkBoxNewBellDay7")
        self.horizontalLayoutNewBellDays.addWidget(self.checkBoxNewBellDay7)
        self.gridLayoutNewBell.addLayout(self.horizontalLayoutNewBellDays, 1, 1, 1, 1)
        self.labelNewBellDays = QtWidgets.QLabel(self.groupBoxNewBell)
        self.labelNewBellDays.setObjectName("labelNewBellDays")
        self.gridLayoutNewBell.addWidget(self.labelNewBellDays, 1, 0, 1, 1)
        self.labelNewBellTime = QtWidgets.QLabel(self.groupBoxNewBell)
        self.labelNewBellTime.setObjectName("labelNewBellTime")
        self.gridLayoutNewBell.addWidget(self.labelNewBellTime, 0, 0, 1, 1)
        self.timeEditNewBellTime = QtWidgets.QTimeEdit(self.groupBoxNewBell)
        self.timeEditNewBellTime.setObjectName("timeEditNewBellTime")
        self.gridLayoutNewBell.addWidget(self.timeEditNewBellTime, 0, 1, 1, 1)
        self.groupBoxNewBellMelody = QtWidgets.QGroupBox(self.groupBoxNewBell)
        self.groupBoxNewBellMelody.setObjectName("groupBoxNewBellMelody")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxNewBellMelody)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBoxNewBellMelody)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 261, 43))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 43))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayoutNewBellSelectMelodyElement = QtWidgets.QHBoxLayout()
        self.horizontalLayoutNewBellSelectMelodyElement.setObjectName("horizontalLayoutNewBellSelectMelodyElement")
        self.radioButtonNewBellSelectMelodyElement = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonNewBellSelectMelodyElement.setObjectName("radioButtonNewBellSelectMelodyElement")
        self.horizontalLayoutNewBellSelectMelodyElement.addWidget(self.radioButtonNewBellSelectMelodyElement)
        self.lineEditNewBellSelectMelodyElement = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditNewBellSelectMelodyElement.setObjectName("lineEditNewBellSelectMelodyElement")
        self.horizontalLayoutNewBellSelectMelodyElement.addWidget(self.lineEditNewBellSelectMelodyElement)
        self.verticalLayout_5.addLayout(self.horizontalLayoutNewBellSelectMelodyElement)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.gridLayoutNewBell.addWidget(self.groupBoxNewBellMelody, 2, 0, 1, 2)
        self.horizontalLayoutSchedulerTab.addWidget(self.groupBoxNewBell)
        self.groupBoxScheduler = QtWidgets.QGroupBox(self.tabScheduler)
        self.groupBoxScheduler.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxScheduler.setFlat(False)
        self.groupBoxScheduler.setCheckable(False)
        self.groupBoxScheduler.setObjectName("groupBoxScheduler")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBoxScheduler)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBoxScheduler)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 648, 64))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 64))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widgetGridScheduler = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widgetGridScheduler.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetGridScheduler.setObjectName("widgetGridScheduler")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetGridScheduler)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSchedulerSaturday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerSaturday.setObjectName("labelSchedulerSaturday")
        self.gridLayout.addWidget(self.labelSchedulerSaturday, 0, 8, 1, 1)
        self.labelSchedulerEnable = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerEnable.setObjectName("labelSchedulerEnable")
        self.gridLayout.addWidget(self.labelSchedulerEnable, 0, 0, 1, 1)
        self.labelSchedulerTime = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerTime.setObjectName("labelSchedulerTime")
        self.gridLayout.addWidget(self.labelSchedulerTime, 0, 2, 1, 1)
        self.pushButtonSchedulerElemPlay = QtWidgets.QPushButton(self.widgetGridScheduler)
        self.pushButtonSchedulerElemPlay.setObjectName("pushButtonSchedulerElemPlay")
        self.gridLayout.addWidget(self.pushButtonSchedulerElemPlay, 1, 0, 1, 1)
        self.labelSchedulerTuesday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerTuesday.setObjectName("labelSchedulerTuesday")
        self.gridLayout.addWidget(self.labelSchedulerTuesday, 0, 4, 1, 1)
        self.labelSchedulerMonday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerMonday.setObjectName("labelSchedulerMonday")
        self.gridLayout.addWidget(self.labelSchedulerMonday, 0, 3, 1, 1)
        self.labelSchedulerFriday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerFriday.setObjectName("labelSchedulerFriday")
        self.gridLayout.addWidget(self.labelSchedulerFriday, 0, 7, 1, 1)
        self.labelSchedulerThursday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerThursday.setObjectName("labelSchedulerThursday")
        self.gridLayout.addWidget(self.labelSchedulerThursday, 0, 6, 1, 1)
        self.pushButtonSchedulerElemDelete = QtWidgets.QPushButton(self.widgetGridScheduler)
        self.pushButtonSchedulerElemDelete.setObjectName("pushButtonSchedulerElemDelete")
        self.gridLayout.addWidget(self.pushButtonSchedulerElemDelete, 1, 10, 1, 1)
        self.timeEditSchedulerElemTime = QtWidgets.QTimeEdit(self.widgetGridScheduler)
        self.timeEditSchedulerElemTime.setObjectName("timeEditSchedulerElemTime")
        self.gridLayout.addWidget(self.timeEditSchedulerElemTime, 1, 2, 1, 1)
        self.labelSchedulerMelody = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerMelody.setObjectName("labelSchedulerMelody")
        self.gridLayout.addWidget(self.labelSchedulerMelody, 0, 1, 1, 1)
        self.lineEditSchedulerElemMelody = QtWidgets.QLineEdit(self.widgetGridScheduler)
        self.lineEditSchedulerElemMelody.setObjectName("lineEditSchedulerElemMelody")
        self.gridLayout.addWidget(self.lineEditSchedulerElemMelody, 1, 1, 1, 1)
        self.labelSchedulerWednesday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerWednesday.setObjectName("labelSchedulerWednesday")
        self.gridLayout.addWidget(self.labelSchedulerWednesday, 0, 5, 1, 1)
        self.labelSchedulerDelete = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerDelete.setObjectName("labelSchedulerDelete")
        self.gridLayout.addWidget(self.labelSchedulerDelete, 0, 10, 1, 1)
        self.labelSchedulerSunday = QtWidgets.QLabel(self.widgetGridScheduler)
        self.labelSchedulerSunday.setObjectName("labelSchedulerSunday")
        self.gridLayout.addWidget(self.labelSchedulerSunday, 0, 9, 1, 1)
        self.checkBoxSchedulerElemMonday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemMonday.setText("")
        self.checkBoxSchedulerElemMonday.setTristate(False)
        self.checkBoxSchedulerElemMonday.setObjectName("checkBoxSchedulerElemMonday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemMonday, 1, 3, 1, 1)
        self.checkBoxSchedulerElemTuesday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemTuesday.setText("")
        self.checkBoxSchedulerElemTuesday.setObjectName("checkBoxSchedulerElemTuesday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemTuesday, 1, 4, 1, 1)
        self.checkBoxSchedulerElemWednesday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemWednesday.setText("")
        self.checkBoxSchedulerElemWednesday.setObjectName("checkBoxSchedulerElemWednesday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemWednesday, 1, 5, 1, 1)
        self.checkBoxSchedulerElemThursday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemThursday.setText("")
        self.checkBoxSchedulerElemThursday.setObjectName("checkBoxSchedulerElemThursday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemThursday, 1, 6, 1, 1)
        self.checkBoxSchedulerElemFriday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemFriday.setText("")
        self.checkBoxSchedulerElemFriday.setObjectName("checkBoxSchedulerElemFriday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemFriday, 1, 7, 1, 1)
        self.checkBoxSchedulerElemSaturday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemSaturday.setText("")
        self.checkBoxSchedulerElemSaturday.setObjectName("checkBoxSchedulerElemSaturday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemSaturday, 1, 8, 1, 1)
        self.checkBoxSchedulerElemSunday = QtWidgets.QCheckBox(self.widgetGridScheduler)
        self.checkBoxSchedulerElemSunday.setText("")
        self.checkBoxSchedulerElemSunday.setObjectName("checkBoxSchedulerElemSunday")
        self.gridLayout.addWidget(self.checkBoxSchedulerElemSunday, 1, 9, 1, 1)
        self.verticalLayout_7.addWidget(self.widgetGridScheduler)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.horizontalLayoutSchedulerTab.addWidget(self.groupBoxScheduler)
        self.horizontalLayout.addLayout(self.horizontalLayoutSchedulerTab)
        self.tabsWidget.addTab(self.tabScheduler, "")
        self.tabDisables = QtWidgets.QWidget()
        self.tabDisables.setObjectName("tabDisables")
        self.tabsWidget.addTab(self.tabDisables, "")
        self.verticalLayoutMain.addWidget(self.tabsWidget)
        self.horizontalLayoutFastActions = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFastActions.setObjectName("horizontalLayoutFastActions")
        self.pushButtonRecord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.horizontalLayoutFastActions.addWidget(self.pushButtonRecord)
        self.pushButtonFireAlert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFireAlert.setObjectName("pushButtonFireAlert")
        self.horizontalLayoutFastActions.addWidget(self.pushButtonFireAlert)
        self.pushButtonTerrorAttack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTerrorAttack.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonTerrorAttack.setObjectName("pushButtonTerrorAttack")
        self.horizontalLayoutFastActions.addWidget(self.pushButtonTerrorAttack)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutFastActions)
        self.horizontalLayoutAudioPlayer = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAudioPlayer.setObjectName("horizontalLayoutAudioPlayer")
        self.pushButtonMainAudioPlayerPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMainAudioPlayerPlay.setObjectName("pushButtonMainAudioPlayerPlay")
        self.horizontalLayoutAudioPlayer.addWidget(self.pushButtonMainAudioPlayerPlay)
        self.progressBarMainAudioPlayer = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarMainAudioPlayer.setProperty("value", 0)
        self.progressBarMainAudioPlayer.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarMainAudioPlayer.setTextVisible(True)
        self.progressBarMainAudioPlayer.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarMainAudioPlayer.setInvertedAppearance(False)
        self.progressBarMainAudioPlayer.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBarMainAudioPlayer.setObjectName("progressBarMainAudioPlayer")
        self.horizontalLayoutAudioPlayer.addWidget(self.progressBarMainAudioPlayer)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutAudioPlayer)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 22))
        self.menubar.setObjectName("menubar")
        self.menu_program = QtWidgets.QMenu(self.menubar)
        self.menu_program.setObjectName("menu_program")
        MainWindow.setMenuBar(self.menubar)
        self.action_menu_program_settings = QtWidgets.QAction(MainWindow)
        self.action_menu_program_settings.setObjectName("action_menu_program_settings")
        self.action_menu_program_about = QtWidgets.QAction(MainWindow)
        self.action_menu_program_about.setObjectName("action_menu_program_about")
        self.action_menu_program_open_folder = QtWidgets.QAction(MainWindow)
        self.action_menu_program_open_folder.setObjectName("action_menu_program_open_folder")
        self.menu_program.addAction(self.action_menu_program_settings)
        self.menu_program.addAction(self.action_menu_program_about)
        self.menu_program.addAction(self.action_menu_program_open_folder)
        self.menubar.addAction(self.menu_program.menuAction())

        self.retranslateUi(MainWindow)
        self.tabsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

